language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
sudo: false
install:
  - pip install tox-travis
script:
  - tox
notifications:
  slack:
    rooms:
      - readthedocs:y3hjODOi7EIz1JAbD1Zb41sz#random
    on_success: change
    on_failure: always
